name: myapp
description: "A new Flutter project."
publish_to: 'none'

# La siguiente línea define la versión y el número de compilación de tu aplicación.
version: 1.0.0+1

environment:
  # Rango de versiones de SDK de Dart compatibles con el proyecto.
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIREBASE ---
  # Paquetes para la integración con los servicios de Firebase.
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0

  # --- GESTIÓN DE ESTADO ---
  # Nuestro gestor de estado centralizado.
  provider: ^6.1.2

  # --- UI & ESTILO ---
  # Para cargar fuentes personalizadas de Google Fonts.
  google_fonts: ^6.2.1
  # Iconos de estilo iOS.
  cupertino_icons: ^1.0.8
  # Nuestra librería de iconos principal.
  lucide_icons: ^0.394.0

  # --- UTILIDADES ---
  # Para formatear fechas y números (ej. en OrderStatusView).
  intl: ^0.19.0
  # Para generar IDs únicos (ej. en CartItem).
  uuid: ^4.4.0
  # Para funciones de extensión de colecciones (ej. firstWhereOrNull).
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # El paquete "flutter_lints" contiene un conjunto de lints recomendados
  # para fomentar buenas prácticas de codificación.
  flutter_lints: ^4.0.0

# La siguiente sección es específica para Flutter.
flutter:

  # La siguiente línea asegura que la fuente Material Icons esté incluida.
  uses-material-design: true

  # Para añadir assets a tu aplicación, añade una sección de assets como esta.
  # Esta sección es necesaria para que Flutter reconozca las imágenes locales.
  assets:
    # Esta línea le dice a Flutter que incluya todos los archivos
    # que se encuentren dentro de la carpeta assets/images/
    - assets/images/family_box.png